config/routes.rb
Rails.application.routes.draw do
  
  

  resources :brands
  resources :colors
  resources :subcategories
  devise_for :admins
  namespace :myadmin do
  get 'admin/index'
  end

  resources :orders
  get 'users/new'

  get 'home/index'
  get 'home/delete_sub'

  match '/payu_callback' => 'payments#payu_return', :via => [:get, :post], :as => 'payments_payu_return'
  match '/product_search' => 'home#product_search', :via => [:get, :post], :as => 'product_search'
  get  'payments/mypayment'
  get  '/cod_confirmation' => 'payments#cod_confirmation', as: 'cod_confirmation'
  get  '/place_oreder' => 'payments#place_oreder', as: 'place_oreder'
  root 'home#index'
  get  '/product_list' => 'home#product_list', as: 'product_list'
  get  '/filter_listing' => 'home#filter_listing', as: 'filter_listing'
  get  '/productfilter_listing' => 'home#productfilter_listing', as: 'productfilter_listing'
  get  '/item_increase_decrease' => 'line_items#item_increase_decrease', as: 'item_increase_decrease'
  
  
  get  '/product_detail' => 'home#product_detail', as: 'product_detail'
  get  'home/product_update'
  get  'home/check_out'
  get  'home/my_order'
  post 'users/register', to: 'users#register', as: :registration
  post 'users/save_address', to: 'users#save_address', as: :save_address
  post 'users/login', to: 'users#login', as: :login
  get 'users/sign_out', to: 'users#sign_out', as: :sign_out
  get 'users/my_profile', to: 'users#my_profile', as: :profile

  resources :line_items do
    get 'decrease', on: :member
    get 'increase', on: :member
  end
  resources :line_items
  resources :carts
  resources :products
  resources :categories

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :user
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/brand.rb
class Brand < ActiveRecord::Base
	has_many :product_brands
	has_many :products, through: :product_brands
end

app/models/cart.rb
class Cart < ActiveRecord::Base
	has_many :line_items, dependent: :destroy

	  def add_product(product_id)
       current_item = line_items.find_by(product_id: product_id)
       if current_item
         current_item.quantity += 1
       else
         current_item = line_items.build(product_id: product_id)
       end
       current_item
    end

    def incr_product(product)
      current_item = line_items.find_by(product_id: product.id)
      if current_item
        current_item.quantity += 1
      else
        current_item = line_items.build(product_id: product.id)
      end
      current_item
  end

  def decr_product(product)
      current_item = line_items.find_by(product_id: product.id)
      if current_item.quantity > 1
        current_item.quantity -= 1
      elsif current_item.quantity = 1
        current_item.destroy
      end
      current_item
  end

    def total_price
     line_items.to_a.sum { |item| item.total_price }
    end
end

app/models/category.rb
class Category < ActiveRecord::Base
	# has_many :products
	has_many :subcategories
	mount_uploader :image_url, ImageUploader
end

app/models/color.rb
class Color < ActiveRecord::Base
	has_many :product_colors
	has_many :products, through: :product_colors
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart
  belongs_to :order

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :user
  has_many :line_items, dependent: :destroy
  PAYMENT_TYPES = [ "Check", "Credit card", "Purchase order" ]

    def add_line_items_from_cart(cart)
     cart.line_items.each do |item|
       item.cart_id = nil
       line_items << item
     end
    end
end

app/models/payment.rb
class Payment < ActiveRecord::Base
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :subcategory
  has_many :line_items
  has_many :product_colors, :dependent => :destroy
  has_many :colors, through: :product_colors
  accepts_nested_attributes_for :product_colors, :allow_destroy => true, :reject_if => :all_blank
  has_many :product_brands, :dependent => :destroy
  has_many :brands, through: :product_brands
  accepts_nested_attributes_for :product_brands, :allow_destroy => true, :reject_if => :all_blank
  
  # before_destroy :ensure_not_referenced_by_any_line_item

  mount_uploader :image_url, ImageUploader

 private

 def ensure_not_referenced_by_any_line_item
	if line_items.empty?
	   return true
	else
	   errors.add(:base, 'Line Items present')
	   return false
	 end
  end
 
end

app/models/product_brand.rb
class ProductBrand < ActiveRecord::Base
  belongs_to :product
  belongs_to :brand
end

app/models/product_color.rb
class ProductColor < ActiveRecord::Base
  belongs_to :product
  belongs_to :color
end

app/models/subcategory.rb
class Subcategory < ActiveRecord::Base
  belongs_to :category
  has_many :products

  mount_uploader :image_url, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
	has_one :user
	before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum: 50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence: true, length: { minimum: 6 }
end

app/controllers/subcategories_controller.rb
class SubcategoriesController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_subcategory, only: [:show, :edit, :update, :destroy]
  layout "myadminlayout"

  # GET /subcategories
  # GET /subcategories.json
  def index
    @subcategories = Subcategory.all
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /subcategories/1
  # GET /subcategories/1.json
  def show
  end

  # GET /subcategories/new
  def new
    @subcategory = Subcategory.new
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # GET /subcategories/1/edit
  def edit
    @categories = Category.all.map{|c| [ c.name, c.id ] }
  end

  # POST /subcategories
  # POST /subcategories.json
  def create
    @subcategory = Subcategory.new(subcategory_params)
    @subcategory.category_id = params[:category_id]

    respond_to do |format|
      if @subcategory.save
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully created.' }
        format.json { render :show, status: :created, location: @subcategory }
      else
        format.html { render :new }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subcategories/1
  # PATCH/PUT /subcategories/1.json
  def update
    @subcategory.category_id = params[:category_id]
    respond_to do |format|
      if @subcategory.update(subcategory_params)
        format.html { redirect_to @subcategory, notice: 'Subcategory was successfully updated.' }
        format.json { render :show, status: :ok, location: @subcategory }
      else
        format.html { render :edit }
        format.json { render json: @subcategory.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subcategories/1
  # DELETE /subcategories/1.json
  def destroy
    @subcategory.destroy
    respond_to do |format|
      format.html { redirect_to subcategories_url, notice: 'Subcategory was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subcategory
      @subcategory = Subcategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def subcategory_params
      params.require(:subcategory).permit(:name, :description, :image_url, :active, :category_id)
    end
end

app/helpers/brands_helper.rb
module BrandsHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/helpers/subcategories_helper.rb
module SubcategoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/subcategories/_form.html.erb
<div class="container-fluid">
<%= form_for(@subcategory) do |f| %>
  <% if @subcategory.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@subcategory.errors.count, "error") %> prohibited this subcategory from being saved:</h2>

      <ul>
      <% @subcategory.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table id="pro_table" style="width:50%">
  <tr>
    <td><%= f.label :name %><br></td>
    <td><%= f.text_field :name %></td> 
  </tr>
  <tr>
    <td><%= f.label :description %><br></td>
    <td><%= f.text_area :description %></td> 
  </tr>
  <tr>
    <td><%= f.label :image_url %><br></td>
    <td><%= f.file_field :image_url %></td> 
  </tr>
  <tr>
    <td><%= f.label :active %><br></td>
    <td><%= f.check_box :active %></tr> 
  </tr>

  <tr>
    <td><%= f.label :Category %><br></td>
    <td> <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select category",:required => true) %></tr> 
  </tr>
  
  <tr>
    <td><%= f.submit :class => "btn btn-warning" %></td>
     
  </tr>

</table>

  <!-- <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br>
    <%= f.file_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :active %><br>
    <%= f.check_box :active %>
  </div>
  <div class="field">
    <%= select_tag(:category_id, options_for_select(@categories), :prompt => "Select category",:required => true) %>
  </div>
  <!-- <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div> -->
  <!-- <div class="actions"> -->
    <%#= f.submit %>
  <!-- </div> --> -->
<% end %>
</div>
<style type="text/css">
#pro_table 
{
    border-collapse:separate;
    border-spacing:0 5px;

}

</style>

app/views/subcategories/edit.html.erb
<div class="container-fluid">

<h1>Editing Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Show', @subcategory ,{:class => "btn btn-primary"} %> |
<%= link_to 'Back', subcategories_path ,{:class => "btn btn-primary"} %>
</div>

app/views/subcategories/index.html.erb
<div class="container-fluid">
<p id="notice"><%= notice %></p>

<h1>Listing Subcategories</h1>

<table class="table table-bordred table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Image url</th>
      <th>Active</th>
      <th>Category</th>
      <th colspan="3" style="padding-left:64px;">Action</th>
    </tr>
  </thead>

  <tbody>
    <% @subcategories.each do |subcategory| %>
      <tr>
        <td><%= subcategory.name %></td>
        <td><%= subcategory.description %></td>
        <td><%= image_tag(subcategory.image_url, class: 'list_image', width: "30px" ,heigth: "30px") %></td>
        <td><%= subcategory.active %></td>
        <td><%= subcategory.category.name %></td>
        <td><%= link_to 'Show', subcategory ,{:class => "btn btn-success"} %>
        <%= link_to 'Edit', edit_subcategory_path(subcategory) ,{:class => "btn btn-info"}%>
        <%= link_to 'Destroy', subcategory,:class => "btn btn-danger", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Subcategory', new_subcategory_path ,{:class => "btn btn-primary"}%>
</div>

app/views/subcategories/new.html.erb
<h1>New Subcategory</h1>

<%= render 'form' %>

<%= link_to 'Back', subcategories_path ,{:class => "btn btn-primary"}%>

app/views/subcategories/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container-fluid">
<table id="pro_table">
  <tr>
    <td><strong>Name:</strong></td>
    <td><%= @subcategory.name %></td> 
  </tr>

  <tr>
    <td><strong>Description:</strong></td>
    <td><%= @subcategory.description %></td> 
  </tr>

  <tr>
    <td><strong>Image:</strong></td>
    <td><%= image_tag @subcategory.image_url.medium5x5.url ,width: "60px",height: "60px" %></td> 
  </tr>

  <tr>
    <td><strong>Active:</strong></td>
    <td><%= @subcategory.active %></td> 
  </tr>


  <tr>
    <td><%= link_to 'Edit', edit_subcategory_path(@subcategory),{:class => "btn btn-primary"} %> |
    <%= link_to 'Back', subcategories_path,{:class => "btn btn-primary"} %></td> 
  </tr>
</table>
<!-- <p>
  <strong>Name:</strong>
  <%= @subcategory.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @subcategory.description %>
</p>

<p>
  <strong>Image url:</strong>
  <%= image_tag @subcategory.image_url.medium5x5.url %>
  <%#= image_tag(@subcategory.image_url, class: 'list_image', width: "30px" ,heigth: "30px") %>
</p>

<p>
  <strong>Active:</strong>
  <%= @subcategory.active %>
</p>

<p>
  <strong>Category:</strong>
  <%= @subcategory.category.name %>
</p>

<%= link_to 'Edit', edit_subcategory_path(@subcategory) %> |
<%= link_to 'Back', subcategories_path %> -->
</div>
<style type="text/css">
#pro_table 
{
    border-collapse:separate;
    border-spacing:0 5px;
}
</style>